### ISSUE TITLE
Integration of the Fuzzer

### ISSUE THREAD

**Issue by hellgheast** [darkmentorllc/jackbnimble#1]
Hello,

I would like to know if there's an update incoming to integrate the LL fuzzer you've developed.

Best Regards,
Ismail

**Comment by darkmentorllc** [comment]
Hello Ismail, 

Unfortunately, I didn’t plan to share the fuzzing code (because 1. it was a simple dumb fuzzer and 2. it should be straight forward to extend the current code as a fuzzer)

Best,
Veronica
